select MEMBER_NAME, rr.REVIEW_TEXT, date_format(rr.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
from REST_REVIEW rr left join MEMBER_PROFILE mr using(MEMBER_ID)
where MEMBER_ID in(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(rr.REVIEW_ID) = (
        SELECT COUNT(REVIEW_ID) 
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
        LIMIT 1
    )
)
order by REVIEW_DATE, REVIEW_TEXT