-- 코드를 입력하세요
SELECT A.BOOK_ID AS BOOK_ID, B.AUTHOR_NAME AS AUTHOR_NAME,DATE_FORMAT(A.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A join AUTHOR B using(AUTHOR_ID)
where A.CATEGORY = '경제'
order by A.PUBLISHED_DATE